name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name : Download Dataset
      run : cd ${{github.workspace}} && bash scripts/download_dataset.sh 
      
    - name : Install libtorch
      run : cd ${{github.workspace}} && sudo bash scripts/install_libtorch.sh   
      
    - name: Configure CMake
      run: mkdir -p ${{github.workspace}}/build && cd ${{github.workspace}}/build && cmake -DCMAKE_PREFIX_PATH=/usr/local/libtorch .. && cmake --build . --config Release 

    - name: Test
      run: cd ${{github.workspace}}/build && ./nanogpt

